[package]
name = "rusty-pass"
version = "0.1.0"
edition = "2021"

[dependencies]
rpassword = "7.3"
aes = "0.8"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
clap = { version = "4.4", features = ["derive"] }
generic-array = "0.14"
